name: 'Compile LLVM and Clang'
description: 'Downloads and Compiles LLVM and Clang binaries.'

inputs:
  version:
    description: 'The version of LLVM and Clang binaries to Compile.'
    required: true
  directory:
    description: 'The directory to Compile LLVM and Clang binaries to.'
    required: true
  cached:
    description: 'Whether the LLVM and Clang binaries were cached.'
    required: false

outputs:
  version:
    description: 'The full version of LLVM and Clang binaries Compileed.'

runs:
  using: 'node12'
  main: 'dist/index.js'
