name: Build LLVM

on:
 [ push ]

jobs:
  build:
    name: Build LLVM
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          # - os: macos-latest
          - os: windows-latest
    steps:
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/llvm/4.0.1
          key: ${{ matrix.os }}-llvm-test
      - name: Build LLVM and Clang
        uses: shekohex/compile-llvm-action@master
        with:
          version: '4.0.1'
          directory: ${{ runner.temp }}/llvm/4.0.1
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: LLVM Version (Windows)
        if: matrix.os == 'windows-latest'
        run: ${{ runner.temp }}/llvm/4.0.1/build/bin/llvm-config.exe --version
      - name: LLVM Version (Unix)
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: ${{ runner.temp }}/llvm/4.0.1/build/bin/llvm-config --version
